# Alocação de memória para mobile (Modo Sobrevivência 1GB)
org.gradle.jvmargs=-Xmx1024m -XX:+UseG1GC -XX:MaxMetaspaceSize=256m -Dfile.encoding=UTF-8

# Economia extrema de recursos no celular
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.daemon=true

# AndroidX e estilo Kotlin
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Silencia aviso de incompatibilidade do compileSdk 36 com AGP 8.5
android.suppressUnsupportedCompileSdk=36

